# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envoy_carrier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envoy_carrier.proto',
  package='lightstep.envoy',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x65nvoy_carrier.proto\x12\x0flightstep.envoy\"\xff\x01\n\x0c\x45nvoyCarrier\x12\x10\n\x08trace_id\x18\x02 \x01(\x06\x12\x0f\n\x07span_id\x18\x03 \x01(\x06\x12\x0f\n\x07sampled\x18\x04 \x01(\x08\x12\x46\n\rbaggage_items\x18\x05 \x03(\x0b\x32/.lightstep.envoy.EnvoyCarrier.BaggageItemsEntry\x12>\n\x12\x64\x65precated_context\x18\x01 \x03(\x0b\x32\".lightstep.envoy.LegacyCarrierPair\x1a\x33\n\x11\x42\x61ggageItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x11LegacyCarrierPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENVOYCARRIER_BAGGAGEITEMSENTRY = _descriptor.Descriptor(
  name='BaggageItemsEntry',
  full_name='lightstep.envoy.EnvoyCarrier.BaggageItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lightstep.envoy.EnvoyCarrier.BaggageItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='lightstep.envoy.EnvoyCarrier.BaggageItemsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=296,
)

_ENVOYCARRIER = _descriptor.Descriptor(
  name='EnvoyCarrier',
  full_name='lightstep.envoy.EnvoyCarrier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='lightstep.envoy.EnvoyCarrier.trace_id', index=0,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='span_id', full_name='lightstep.envoy.EnvoyCarrier.span_id', index=1,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampled', full_name='lightstep.envoy.EnvoyCarrier.sampled', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baggage_items', full_name='lightstep.envoy.EnvoyCarrier.baggage_items', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_context', full_name='lightstep.envoy.EnvoyCarrier.deprecated_context', index=4,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ENVOYCARRIER_BAGGAGEITEMSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=296,
)


_LEGACYCARRIERPAIR = _descriptor.Descriptor(
  name='LegacyCarrierPair',
  full_name='lightstep.envoy.LegacyCarrierPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lightstep.envoy.LegacyCarrierPair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='lightstep.envoy.LegacyCarrierPair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=345,
)

_ENVOYCARRIER_BAGGAGEITEMSENTRY.containing_type = _ENVOYCARRIER
_ENVOYCARRIER.fields_by_name['baggage_items'].message_type = _ENVOYCARRIER_BAGGAGEITEMSENTRY
_ENVOYCARRIER.fields_by_name['deprecated_context'].message_type = _LEGACYCARRIERPAIR
DESCRIPTOR.message_types_by_name['EnvoyCarrier'] = _ENVOYCARRIER
DESCRIPTOR.message_types_by_name['LegacyCarrierPair'] = _LEGACYCARRIERPAIR

EnvoyCarrier = _reflection.GeneratedProtocolMessageType('EnvoyCarrier', (_message.Message,), dict(

  BaggageItemsEntry = _reflection.GeneratedProtocolMessageType('BaggageItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _ENVOYCARRIER_BAGGAGEITEMSENTRY,
    __module__ = 'envoy_carrier_pb2'
    # @@protoc_insertion_point(class_scope:lightstep.envoy.EnvoyCarrier.BaggageItemsEntry)
    ))
  ,
  DESCRIPTOR = _ENVOYCARRIER,
  __module__ = 'envoy_carrier_pb2'
  # @@protoc_insertion_point(class_scope:lightstep.envoy.EnvoyCarrier)
  ))
_sym_db.RegisterMessage(EnvoyCarrier)
_sym_db.RegisterMessage(EnvoyCarrier.BaggageItemsEntry)

LegacyCarrierPair = _reflection.GeneratedProtocolMessageType('LegacyCarrierPair', (_message.Message,), dict(
  DESCRIPTOR = _LEGACYCARRIERPAIR,
  __module__ = 'envoy_carrier_pb2'
  # @@protoc_insertion_point(class_scope:lightstep.envoy.LegacyCarrierPair)
  ))
_sym_db.RegisterMessage(LegacyCarrierPair)


_ENVOYCARRIER_BAGGAGEITEMSENTRY.has_options = True
_ENVOYCARRIER_BAGGAGEITEMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
